// src/components/App.tsx
import React, { useState } from "react";
import "./App.css";

import Installation from "./Installation";

import { Processor, Firmware } from "../types";

import EnumRadio from "./EnumRadio";

const App = () => {
  const [processor, setProcessor] = useState(Processor.AMD);
  const [firmware, setFirmware] = useState(Firmware.UEFI);

  const params = {
    username: useState("zach"),
    hostname: useState("ballz-pc"),
    partition_device: useState("/dev/sdX"),
    partition_efi: useState("/dev/sdX1"),
    partition_root: useState("/dev/sdX2")
  };

  return (
    <>
      <div className="controls" style={{ marginBottom: "2rem" }}>
        <ol>
          <li>
            <EnumRadio
              name="firmware"
              options={Firmware}
              value={firmware}
              onChange={setFirmware}
            />
          </li>
          {firmware === Firmware.UEFI && (
            <li>
              <EnumRadio
                name="processor"
                options={Processor}
                value={processor}
                onChange={setProcessor}
              />
            </li>
          )}
        </ol>
        {Object.entries(params).map(([name, [value, setValue]]) => (
          <input
            key={name}
            type="text"
            value={value}
            onChange={event => setValue(event.target.value)}
          />
        ))}
      </div>
      <h1>Installation cheatsheet</h1>
      <div className="App">
        <Installation
          firmware={firmware}
          processor={processor}
          username={params["username"][0]}
          hostname={params["hostname"][0]}
          partition_device={params["partition_device"][0]}
          partition_efi={params["partition_efi"][0]}
          partition_root={params["partition_root"][0]}
        />
      </div>
    </>
  );
};

export default App;

// src/App.svelte
<script>
  import Installation from "./components/Installation.svelte";
  import EnumRadio from "./components/EnumRadio.svelte";

  let keymap = "dk";
  let locale = "en_DK";
  let processor = "AMD";
  let firmware = "UEFI";
  let username = "zach";
  let hostname = "ballz-pc";
  let partitionDevice = "/dev/sdX";
  let partitionBoot = "/dev/sdX1";
  let partitionRoot = "/dev/sdX2";
  let editor = "vim";

  $: isUEFI = firmware === "UEFI";
</script>

<style>
  @media print {
    .controls {
      display: none;
    }
  }
</style>

<div>
  <ol class="controls">
    <li>
      <EnumRadio options={['UEFI', 'BIOS']} bind:value={firmware} />
    </li>
    <li>
      <EnumRadio options={['AMD', 'Intel']} bind:value={processor} />
    </li>
    <li>
      <EnumRadio options={['vim', 'nano']} bind:value={editor} />
    </li>
    <li>
      <label>
        Keymap
        <input bind:value={keymap} />
      </label>
    </li>
    <li>
      <label>
        Locale
        <input bind:value={locale} />
      </label>
    </li>
    <li>
      <label>
        Username
        <input bind:value={username} />
      </label>
    </li>
    <li>
      <label>
        Hostname
        <input bind:value={hostname} />
      </label>
    </li>
    <li>
      <label>
        Partition Device
        <input bind:value={partitionDevice} />
      </label>
    </li>
    <li>
      <label>
        Partition Root
        <input bind:value={partitionRoot} />
      </label>
    </li>
    {#if isUEFI}
      <li>
        <label>
          Partition Boot
          <input bind:value={partitionBoot} />
        </label>
      </li>
    {/if}
  </ol>
  <Installation
    {keymap}
    {locale}
    {firmware}
    {processor}
    {username}
    {hostname}
    {partitionDevice}
    {partitionBoot}
    {partitionRoot}
    {editor} />
</div>
